name: Merge Multiarch Container

on:
  workflow_call:
    inputs:
      ghcr_image:
        required: true
        type: string
      model:
        required: true
        type: string
      latest:
        default: false
        type: boolean

permissions:
  packages: write
  contents: write
  id-token: write
  attestations: write

jobs:
  merge:
    runs-on: ubuntu-latest
    env:
      GHCR_IMAGE: ${{ inputs.ghcr_image }}
    steps:
      - name: Download digests for model ${{ inputs.model }}
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*-${{ inputs.model }}
          merge-multiple: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set metadata for container build
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GHCR_IMAGE }}
          tags: |
            type=raw,value=${{ inputs.model }}
            type=raw,value=latest,enable=${{ inputs.latest }}

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.GHCR_IMAGE }}@sha256:%s ' *)

      - name: Get final merged image digest
        run: |
          DIGEST=$(docker buildx imagetools inspect ${{ env.GHCR_IMAGE }}:${{ inputs.model }} --format '{{ json .Manifest.Digest }}' | tr -d '"')
          echo "MERGED_DIGEST=$DIGEST" >> $GITHUB_ENV

      - name: Generate attestation for merged multiarch image
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.GHCR_IMAGE }}
          subject-digest: ${{ env.MERGED_DIGEST }}
          push-to-registry: true
